/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:c08fbc0d-bbb0-4049-8c10-e78c2ad5914c",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_nJpPFB8CI",
    "aws_user_pools_web_client_id": "6cu600nrhhoqirsiqanuhj3l22",
    "oauth": {}
};


export default awsmobile;
